> ### **Assignment 2 - Numpy Array Operations** 
>
> This assignment is part of the course ["Data Analysis with Python: Zero to Pandas"](http://zerotopandas.com). The objective of this assignment is to develop a solid understanding of Numpy array operations. In this assignment you will:
> 
> 1. Pick 5 interesting Numpy array functions by going through the documentation: https://numpy.org/doc/stable/reference/routines.html 
> 2. Run and modify this Jupyter notebook to illustrate their usage (some explanation and 3 examples for each function). Use your imagination to come up with interesting and unique examples.
> 3. Upload this notebook to your Jovian profile using `jovian.commit` and make a submission here: https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas/assignment/assignment-2-numpy-array-operations
> 4. (Optional) Share your notebook online (on Twitter, LinkedIn, Facebook) and on the community forum thread: https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575 . 
> 5. (Optional) Check out the notebooks [shared by other participants](https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575) and give feedback & appreciation.
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.
>
> Try to give your notebook a catchy title & subtitle e.g. "All about Numpy array operations", "5 Numpy functions you didn't know you needed", "A beginner's guide to broadcasting in Numpy", "Interesting ways to create Numpy arrays", "Trigonometic functions in Numpy", "How to use Python for Linear Algebra" etc.
>
> **NOTE**: Remove this block of explanation text before submitting or sharing your notebook online - to make it more presentable.


# Useful Top 5 Numpy Array Operations


### NumPy is a python library which is extensively used for working with arrays and manipulating them. It is used to work with complex computations which are generally perfomed in a few branches of Mathematics.

- reshape
- transpose
- split
- tile
- flip

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

In [1]:
!pip install jovian --upgrade -q

In [2]:
import jovian

In [3]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Please enter your API key ( from https://jovian.ml/ ):
API KEY: ········
[jovian] Updating notebook "hemanth-kotagiri/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/hemanth-kotagiri/numpy-array-operations


'https://jovian.ml/hemanth-kotagiri/numpy-array-operations'

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [5]:
import numpy as np

In [6]:
# List of functions explained 
function1 = np.reshape
function2 = np.transpose
function3 = np.split
function4 = np.tile
function5 = np.flip

## Function 1 - np.reshape

This function gives a new shape to the given array without changing the values in the array

In [13]:
a = np.ones((10,2))
function1(a, (2,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

The above function will reshape the shape of the array with the dimensions specified

In [16]:
# Example 2 - working
b = [[1, 2, 3], 
     [4, 5, 6]]
function1(b, (3, 2))

array([[1, 2],
       [3, 4],
       [5, 6]])

The above does the same

In [17]:
# Example 3 - breaking (to illustrate when it breaks)
arr1 = [[1, 2], 
        [3, 4.]]

arr2 = [[5, 6, 7], 
        [8, 9, 10]]

function1(arr1, (2,3))

ValueError: cannot reshape array of size 4 into shape (2,3)

The above breaks because we have specified an invalid dimensions for the given array

It's clear that we can very easily change the shape of an array using numpy's reshape function

In [18]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "hemanth-kotagiri/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/hemanth-kotagiri/numpy-array-operations


'https://jovian.ml/hemanth-kotagiri/numpy-array-operations'

## Function 2 - Transpose

This function transposes the given array

In [20]:
# Example 1 - working
a = [[1, 4, 56],
     [2, 5, 6]]

function2(a)

array([[ 1,  2],
       [ 4,  5],
       [56,  6]])

As we can see the given array shape was (2 X 3) and when we perfom the transpose, we get 3X2 as the output

In [25]:
# Example 2 - working
a = np.ones((1,10))
print(a)
function2(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

Explanation about example

In [36]:
# Example 3 - breaking (to illustrate when it breaks)
b = [[1, 2], [3, 4]]

function2(b, axes=(2,2))

AxisError: axis 2 is out of bounds for array of dimension 2

The above breaks because we are specifying an out of bound number for the axes considering the dimensions of the array

Some closing comments about when to use this function.

In [37]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "hemanth-kotagiri/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/hemanth-kotagiri/numpy-array-operations


'https://jovian.ml/hemanth-kotagiri/numpy-array-operations'

## Function 3 - Split

This function splits an array into multiple sub-arrays

In [43]:
# Example 1 - working
a = np.ones(9)
function3(a, 3)

[array([1., 1., 1.]), array([1., 1., 1.]), array([1., 1., 1.])]

The above splits the array a into three equal divisions

In [45]:
# Example 2 - working
b = np.eye(10)
function3(b, 5)

[array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]]),
 array([[0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.]]),
 array([[0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.]]),
 array([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.]]),
 array([[0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])]

We can also split it on any square matrix as shown above which has a dimension which is divisible by the value we pass for the function3

In [54]:
# Example 3 - breaking (to illustrate when it breaks)
c = np.random.randint(40, size=(5,5))
function3(c, 2)

ValueError: array split does not result in an equal division

The above breaks because we have a 5x5 matrix and we're trying to split it into 2 which does not result in an equal division. Hence, we can fix it by changing the value to 1

We can use this function when we want to split a huge dataset for training and validation splits given that the dataset is randomly shuffled

In [56]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "hemanth-kotagiri/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/hemanth-kotagiri/numpy-array-operations


'https://jovian.ml/hemanth-kotagiri/numpy-array-operations'

## Function 3 - Split

This function splits an array into multiple sub-arrays

In [57]:
# Example 1 - working
a = np.ones(9)
function3(a, 3)

[array([1., 1., 1.]), array([1., 1., 1.]), array([1., 1., 1.])]

The above splits the array a into three equal divisions

In [58]:
# Example 2 - working
b = np.eye(10)
function3(b, 5)

[array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]]),
 array([[0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.]]),
 array([[0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.]]),
 array([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.]]),
 array([[0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])]

We can also split it on any square matrix as shown above which has a dimension which is divisible by the value we pass for the function3

In [59]:
# Example 3 - breaking (to illustrate when it breaks)
c = np.random.randint(40, size=(5,5))
function3(c, 2)

ValueError: array split does not result in an equal division

The above breaks because we have a 5x5 matrix and we're trying to split it into 2 which does not result in an equal division. Hence, we can fix it by changing the value to 1

Some closing comments about when to use this function.

In [60]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "hemanth-kotagiri/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/hemanth-kotagiri/numpy-array-operations


'https://jovian.ml/hemanth-kotagiri/numpy-array-operations'

## Function 4 - Tile

Returns a new array by recreating the specified array by adding redundant values for a specified times

In [67]:
# Example 1 - working
a = np.array([10, 20, 30])
function4(a, 4)

array([10, 20, 30, 10, 20, 30, 10, 20, 30, 10, 20, 30])

It is evident that, the values in the array are redundantly added at the end of the list for the given reps(in this case, 4) and returned as a new array

In [72]:
# Example 2 - working
b = np.array([[10, 20], [30, 40]])
function4(b, (3,1))

array([[10, 20],
       [30, 40],
       [10, 20],
       [30, 40],
       [10, 20],
       [30, 40]])

We can also perform the same on more than one dimensional matrices as shown above

In [83]:
# Example 3 - breaking (to illustrate when it breaks)
c = np.eye(5)
function4(c, 2, 2)

TypeError: _tile_dispatcher() takes 2 positional arguments but 3 were given

The above breaks because we aren't passing the reps as a tuple. By passing the reps as => (2, 2) the error would be fixed

Some closing comments about when to use this function.

In [84]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "hemanth-kotagiri/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/hemanth-kotagiri/numpy-array-operations


'https://jovian.ml/hemanth-kotagiri/numpy-array-operations'

## Function 5 - flip

Reverses the order of elements in a given array

In [96]:
# Example 1 - working
a = np.arange(8).reshape((2,2,2))
print(a)
function5(a, 0)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


array([[[4, 5],
        [6, 7]],

       [[0, 1],
        [2, 3]]])

The above flips by swapping both the individual arrays inside the given array.

In [98]:
# Example 2 - working
b = [[1, 2], 
     [3, 4]]
function5(b, 1)

array([[2, 1],
       [4, 3]])

The above swaps the elements in the list diagonally.

In [104]:
# Example 3 - breaking (to illustrate when it breaks)
c = [[1.4, 2.22],
     [6.5, 3.323]]

function5(c, 2)

AxisError: axis 2 is out of bounds for array of dimension 2

The above example breaks because we are passing an axis of 2 which is out of the array dimensions. To fix this, we can pass the value as 1 or 0

Some closing comments about when to use this function.

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..


## Conclusion

Summarize what was covered in this notebook, and where to go next

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* ...

In [30]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-array-operations


'https://jovian.ml/aakashns/numpy-array-operations'